language: go

go:
  - 1.7

install:
  - go get github.com/ant0ine/go-json-rest/rest
  - go get github.com/go-sql-driver/mysql
  - go get github.com/BurntSushi/toml

test:
  - go build rest-server.go
  - go test -v ./
